# 交叉编译配置
# x86_64 编译不受影响

# 统一使用 armv7-unknown-linux-gnueabihf target
# linker 默认使用通用 arm-linux-gnueabihf-gcc
# rv1106 模式通过 build_rv1106.sh 设置 CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER 覆盖
[target.armv7-unknown-linux-gnueabihf]
linker = "armv7l-linux-gnueabihf-gcc"
