relays = [
    "/ip4/101.35.90.171/udp/4001/quic-v1/p2p/12D3KooWDGUejVsts1G4tGyf8ukkr73eWxCr1EUfCQxgcbSDUie1",
    "/ip4/101.35.90.171/tcp/4001/p2p/12D3KooWDGUejVsts1G4tGyf8ukkr73eWxCr1EUfCQxgcbSDUie1",
]
relay = ""
enable_mdns = true
cameras = [
    "12D3KooWG2ihY7Ne75KqkYyYrQWL1ACLUgUN8rp1nTskQB3RNNNt",
    "12D3KooWG2ihY7Ne75KqkYyYrQWL1ACLUgUN8rp1nTskQB3RNaaa",
]
camera = ""
stream = "auto"
no_audio = false
play = true
network_type = "auto"
