enable_mdns = true
camera_serials = [
    "e33700a6620dfddc",
    "12D3KooWG2ihY7Ne75KqkYyYrQWL1ACLUgUN8rp1nTskQB3RNNNt",
    "1234567890888888",
]
stream = "auto"
no_audio = false
play = true
network_type = "auto"

[[relay_list]]
name = "中继1-QUIC"
ip = "101.35.90.171"
port = 4001
transport = "quic"
peer_id = "12D3KooWDGUejVsts1G4tGyf8ukkr73eWxCr1EUfCQxgcbSDUie1"

[[relay_list]]
name = "中继1-TCP"
ip = "101.35.90.171"
port = 4001
transport = "tcp"
peer_id = "12D3KooWDGUejVsts1G4tGyf8ukkr73eWxCr1EUfCQxgcbSDUie1"

[[relay_list]]
name = "中继2-QUIC"
ip = "124.221.175.240"
port = 4001
transport = "quic"
peer_id = "12D3KooWBko9VUfuMVEMUFcVaktZxEY48MZTeDTEMUgz4op86qUv"

[[relay_list]]
name = "中继2-TCP"
ip = "124.221.175.240"
port = 4001
transport = "tcp"
peer_id = "12D3KooWBko9VUfuMVEMUFcVaktZxEY48MZTeDTEMUgz4op86qUv"

[[relay_list]]
name = "中继2-IPv6-QUIC"
ip = "2402:4e00:c032:2400:3afc:b786:56a4:0"
port = 4001
transport = "quic"
peer_id = "12D3KooWBko9VUfuMVEMUFcVaktZxEY48MZTeDTEMUgz4op86qUv"

[[relay_list]]
name = "中继2-IPv6-TCP"
ip = "2402:4e00:c032:2400:3afc:b786:56a4:0"
port = 4001
transport = "tcp"
peer_id = "12D3KooWBko9VUfuMVEMUFcVaktZxEY48MZTeDTEMUgz4op86qUv"

[serial_map]
e33700a6620dfddc = "12D3KooWG2ihY7Ne75KqkYyYrQWL1ACLUgUN8rp1nTskQB3RNNNt"
